name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn run build
              env:
                  REACT_APP_BACKEND_URL: https://f5dfwrf3a8.execute-api.us-east-2.amazonaws.com/Prod
                  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
            - uses: actions/upload-artifact@v1
              with:
                  name: build
                  path: build
